#!/usr/bin/env ansible-playbook
---
- hosts: client
  roles:
    - utils
    - client
    
- hosts: master
  roles:
    - utils
    - dns_maitre

- hosts: slave
  roles:
    - utils
    - dns_esclave 

- hosts: slave_robind
  roles:
    - utils
    - dnsesclave_roundrobind 

- hosts: supervision
  roles:
    - utils
#    - prometheus

...
