---
- name: installation de bind9
  apt:
    name: bind9
    update_cache: yes

- name: changement de l'user root en bind 
  ansible.builtin.file:
    path: /etc/bind
    state: directory 
    owner: bind
    group: bind

- name: ajoute de named.conf.local
  template:
    src: "named.conf.local.j2"
    dest: "/etc/bind/named.conf.local"

- name: ajoute de named.conf.options
  template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"

- name: ajoute de named.conf
  template:
    src: "named.conf.j2"
    dest: "/etc/bind/named.conf"

- name: ajoute de db.projetdns.com
  template:
    src: "db.projetdns.com.j2"
    dest: "/etc/bind/db.projetdns.com"
        
- name: ajoute de db.0.0.10.in-addr.arpa
  template:
    src: "db.0.0.10.in-addr.arpa.j2"
    dest: "/etc/bind/db.0.0.10.in-addr.arpa"

- name: ajoute de resolv.conf
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    
- name: bind9 restart
  ansible.builtin.service:
    name: bind9
    state: restarted
...

