---
- name: installation de bind9
  apt:
    name: bind9
    update_cache: yes

- name: ajoute de named.conf
  template:
    src: "named.conf.j2"
    dest: "/etc/bind/named.conf"

- name: ajoute de named.conf.local
  template:
    src: "named.conf.local.j2"
    dest: "/etc/bind/named.conf.local"

- name: ajoute de resolv.conf
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    
- name: changement de l'user root en bind 
  ansible.builtin.file:
    path: /etc/bind
    state: directory 
    owner: bind
    group: bind
    
- name: bind9 restart
  ansible.builtin.service:
    name: bind9
    state: restarted
...
