---
# les enregistements et leurs ip  
records:
  - { 'name': pc , 'ip': 10.0.0.1 }
  - { 'name': dnsesclave , 'ip': 10.0.0.3 }  
  - { 'name': dnsesclave-roundrobind , 'ip': 10.0.0.6 }

# les enregistement robind et leurs ip
records2:
  - { 'name2': dns.projetdns.com. , 'ip2': 10.0.0.2 }
  - { 'name2': dns.projetdns.com. , 'ip2': 10.0.0.3 }  
  - { 'name2': dns.projetdns.com. , 'ip2': 10.0.0.6 }
  

# les enregistements pour la zone inverse et leurs ip 
records_inv:
  - { 'name': 2 , 'ip': dns.projetdns.com. }
  - { 'name': 3 , 'ip': dnsesclave.projetdns.com. }
  - { 'name': 1 ,'ip': pc.projetdns.com. }
...
